[gspread]
gsheet_key = "1dSLBX28xN5yJe48OIviUy6FgzM96P17AW4LM0Ow03eg"
type = "service_account"
project_id = "analytics-project-survey-forms"
private_key_id = "6b72d2febeca9abeaaccb07a2b3201f3ed61bbf1"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDEomvuCdugaSjf
bka4RvQGoRMMXPgJOXrqA4cIFpcD3F6wH9gwVxLG1igevsR3kf87uvsuxazmF2WY
Yol7gI8Gx/fiHpXsz+vsZ6rYtQlm3i3WehZL/RLRfk1fdFdIQmoLcmupcEH+4VtV
QZ+UbU4pdbEuTSEaf7Nzf34LrsR/+JuW/Qk6aD4r0jEkepVVlVPn7yRtKQhDtV7k
TVlmQDPFGzr1ol3yznA92tIvQZiSyJPZyRu2jhBYpvrVywc01718+lh2186Yz+Wy
tspcAA9qjvJhn8Zc8SLlZE0tW5P/yLOfYZ1dAvGy5sFmc12vqohQ0OY8CePMCmUQ
aA4wafkrAgMBAAECggEAHSiy1aFLmt2NTJjHTvNio4sGTpqIw6Fs+z/bqdTjvxRS
TE7kmcKHy8mdOHX0n4Ccd0iSkAyLR7GnhLH0DkbxrsE/np4HgI8SvsNev/UUuFbx
ODFxlgIo5L0Ujzeq69HBdQIaOg2mE7xqdVmeZv3QjfBgfmu8oXfXbiS1VdksVYeO
xD2GcQwgGBGFr9dlHwSKjm2WgKBOIKWE7XiaNzMZPxKXtMNJzKfPE+KcVJvqs2lk
FDCJnGwCBy2lKPb+5/a4sPMfMm4sCz33qCAmV5zQqaB2bV1WwJBH8ehP2pUlxpZx
HPY74cBlyGsb/PDDFZZMnXWaj7Sy1g2s2/rkRlJwrQKBgQD+jmCZw/ttCH5SH7Iw
/qYAbSWsV28a+GiryzoPJmE//q9Hm0LbS20EM2UjEI5wHiud8Iho2vAJW6kLkaZj
9h8LyzyYVRVT19WEdsQ53n5PjrvwtuzH+O03pUUB82y23xnvfoPYzfUhraofcbPz
XwwHTdrutE/+q84o8PtwlLqebwKBgQDFv/C5NClGCVoRX8OjZ0nmQV8yMfgtrI/Q
2dd9aPE1VahsYgaDkGhsOFrWHNzSd9nIjIcMhoSVLMH48Zxt2hEykM5a36waYrpR
5qVHfbNDpZVx6ZvgPtH5p4GDtI2CX/0geJnI05ZTmeXkevAevr4v/c4msx3wYVnp
LrIcbHmvBQKBgQDevbLlmcntlFsEfVus54ZWJSur7C36SZc9i+zXyNub5b12SPNt
dEiGPnqm/hvFG4FLCGg0aC9V4PDAgMg5++kaptH08a5h2SCqckot4PRhpSHq9gWm
zbi00lbZ6Ckes4W8PNYd5cozmASe0x2FPYwG8Cc8bGb7D1asGIHL9zh83QKBgCfZ
uVIpT9P8WHk92jgYvYy4Sc3cwg26Q7Ur4UA1oL5Fx84npvZmaJS+epfBc0K6wlmm
8CQ3C4rgXSqkzghZNLQC+ILZpl4e3TtaBp60lyafvNEa6b20Cy6Lcg8vmIDYhTNA
+oS9FwM79Vco6zDW8Y7MT/n+iJ8Dj1HthhkyRwddAoGASXsDXcGPz3gnAT3k7DbG
Gh4sgDfx+T+79FIpGBWUoXDQV6O75fEgo6vmoeorI2bJ8Nrmn6U0bRwyhMEljYW6
WVWgmW4bAEnvnrcvdvi3k0x8og03PjNIkj6Iz4tVIzLhfqGWIKwVOKglRwO4ir0h
Om/hZvj/D3Vj3wVylydJQEI=
-----END PRIVATE KEY-----"""
client_email = "gsheets-python-access@analytics-project-survey-forms.iam.gserviceaccount.com"
client_id = "100913703813922958916"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs" 
client_x509_cert_url =  "https://www.googleapis.com/robot/v1/metadata/x509/gsheets-python-access%40analytics-project-survey-forms.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
gsheet_key = "120CdAS6mUd8BMex1ftYZ6pRLsucxFiLlgCQp8PYVRG4"
