[gspread]
type = "service_account"
project_id = "analytics-project-survey-forms"
private_key_id = "250b18e6ffef39517b5ea48d4cfae4547fe2377d"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCqrOYlCDTYgLHf
ZM1GMEUG7cX+3TMP4K5Juh7aMLcvAvx6D0MoBwzcGOqKf2BiMYy3YH5ontioaWB9
fReHEoWJjazkFyYRiDYwaabj+GvO6MCXA0QgS1rLiwCtgOSf3wWGF6W/zWFZgc7u
TraGEYgPISCscXH5vLGachVtSXsSMuttVaKubkWCKFeY57TZpr56gBsqvWw7aOJa
JzniUHwTo4nIqmdqzOsljOL5KMv7jYmOXNKuw3T8Y/IzaA3RIveeupwjg6ZRuVef
RLSfrXtQxCvwKTuBIQo5vPDeSy+YRBbun/8MWdI50lDeN7ac/bjWvvk+UA+D1cNQ
mDKofH8LAgMBAAECggEAAMpHIEvtnKIEmXOphzl2s4u3Zkd0RSbWAwVJHNIzHZaP
fIROOAWmf5i7mqbttkATqcYSQ+MC3mQF+29PHxxVgWb5ETjcWrvTAGZLN4Tc7xjo
fD1QvkF1+IGnBNnQVASPP/IpdP4LoD49AkbN/SdphKLoNUsh75cNndClnj3smtNE
r+SxjEyXc7x6MAGlS227uuB1zZxn2GonwF2jfTuYIG5EVV3+v/LnovltqTpB6qaR
3Z327rKXcI4IDMfOLp3UtYHVFpn57HNJT+u0q8wG698UQafMO5N/vZOj0oY1i25J
lEu6pgO3awMj9NhZ4bK3CgEjQwJXtQtvv72LdchV9QKBgQDwOSnm+5ZO0gPoCYPz
B/FiYgVJ7J9Nvibof1toPDTs5atPH1HES1IHJ2+0iLsiAITyUu7y9RMJO/MOv7v4
jB/6D6RgRgtSChVOaFULmwgkZFUAcasPQ4bapxNIuCLD6pxUGFiEcPjOSJUJNfP1
W8KwXvsqE3xgt240Ay1KpwKyvwKBgQC14m/z+mpEXUkiSTS6tCN4R0WRjHXSb1wr
wJ5PIRnuSMqh0aTGMOZQEgBk+RN75lfhQqZnR3CB36ExIHD3rM1mg8FrqFalr0Uo
/4+SziVYrUqOppXA2QUXHVZ6c+fUhfT4kYu+9XtVOy6stN/7EKcuUO6Z6WHzZsUL
DQ3qCZlitQKBgEBHC29C4nU0vNbZtPTSq0Qn9kJRjk6/EqojadH6Si8ZRT1mo/pi
LRC8/KbR70Cp4uj0R/u6l91grSjFJQbcd7HxfYpFM8I/8HOKdzcjxIn4TsZPo/Xx
m6PmEMLkgmjp3eqimQzXLbwEr9xHE4ATjYSj5ZDcpes7KcHBF91h0tcBAoGAVZWl
RFKS6nRS03VLAId/ITu4OpKzZj/MSTIry+QxhXRvFNHHDRM5bHfsA5dIWca7l117
W6G8CQCnoqw3O/Pt+s0ImJXvn6rnijEm59dkr2Nrb9BnKwVzZbsCVEBx2AjoioZC
EasFS8e7YL0Dn+noIN0oSPgOhS/YjCiqYXP+3vkCgYEAzA/fmvmIjF2zliAtXgz1
uMxq5Dn3XahlpxquOc93tU8tQ5C2t/Q8T4/rLOaYb68Pz3KpVWz5sfOFmHd8tl3U
ZvDLdVY6/fWVRyP3KItIRJ7qYxjrz21Pq+NST0SoAvEC1FAWtSOmdhfPQCnf9igD
MyLrZbEnrG9KTnHsTHbn/UQ=
-----END PRIVATE KEY-----"""
client_email = "gsheets-python-access@analytics-project-survey-forms.iam.gserviceaccount.com"
client_id = "100913703813922958916"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/gsheets-python-access%40analytics-project-survey-forms.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
gsheet_key = "120CdAS6mUd8BMex1ftYZ6pRLsucxFiLlgCQp8PYVRG4"
